FROM golang:1.7.3 as multistage

WORKDIR /go/src/

RUN go get -d -v golang.org/x/net/html

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

##

FROM alpine:latest

RUN apk add --no-cache --update git

WORKDIR /root/

RUN cp /go/src/app .

COPY --from=multistage /go/bin/api /go/bin/

CMD ["./app"]
